Add home work 7
ShevOleks/Shevchenko_JavaBase2023_03-10-2023 pull request #1
Opened 2023-10-12 15:30 UTC by ShevOleks

2023-10-15 18:14 UTC, ShevOleks commented
Home works for lesson 7

2023-10-16 07:22 UTC, JIeIIIa requested changes

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Lottery.java
> +        int[] org = genArray(lengthArr, numRange);
`genArray` -> `generateTicket`

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Lottery.java
> +        int lengthArr = 7;
Не варто використовувати скорочення. Замість `lengthArr` змінну можна було назвати `numberCount`/`ticketLength` тощо (стосується всіх скорочень в роботі)

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Lottery.java
> +
Після того, як масив згенеровано його потрібно було вивести в консоль. Як запустивши твою програму користувачу переконатись, що сортування працює вірно?

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Lottery.java
> +        for (int i = 0; i < length; i++) {
Якщо ти ітеруєшся по індексам масива, то краще пиши `i < arr.length`. Бо завтра умова зміниться і потрібно буде робити `int[] arr = new int[2 * length]`. Де гарантія, що в циклі не забудеш поміняти?

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Transposition1.java
> +        int[][] origArray = new int[dimM][dimN];
Не дивлячись на те, що в умову `N` та `M`, доцільніше було б назвати змінні `columns` та `rows`. Твої назви дуууже легко сплутати

2023-10-16 07:22 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Transposition2.java
> +        for (int i = 0; i < dimM; i++) {
Коли ітеруєшся по індексам масива, то використовуй масив в умовах циклу: `i < arr.length` На лекції розбирали чому краще не робити так, як у тебе в коді.

2023-10-16 22:15 UTC, JIeIIIa commented on src/ua/vodafone/lesson6_7/Lottery.java
> +        int lengthArr = 7;
Виправлено не для всіх змінних (

2023-10-17 07:06 UTC, ShevOleks commented on src/ua/vodafone/lesson6_7/Lottery.java
> +        int lengthArr = 7;
Так, не догледів, мій косяк...
Зараз, наче, все виправив (передивлявся по 2 рази ))

2023-10-26 22:25 UTC, merged