Lesson12 hw18
ShevOleks/Shevchenko_JavaBase2023_03-10-2023 pull request #10
Opened 2023-11-07 18:25 UTC by ShevOleks

2023-11-07 21:44 UTC, JIeIIIa requested changes

2023-11-07 21:44 UTC, JIeIIIa commented on pom.xml
> +    <artifactId>JavaBase_2023</artifactId>
тут так само, як і з пакетами: прийнято використовувати маленькі літери та -

2023-11-07 21:44 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +    private static Point one, two;
правила ті ж самі, що і в класах і в методах: в одному рядку оголошуємо тільки одну змінну. Також ця змінна у тебе використовується у тестах. Теоредично одночасно може запускатись декілька тестів, які ці змінні будуть використовувати. За рахунок того, що змінні статичні можна отримати неочікувані побічні ефекти

2023-11-07 21:44 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertEquals(Math.sqrt(2), result);
кожен раз, коли ми порівнюємо дійсні числа це потрібно робити з певною точністю. у `assertEquals` є перевантажений (overloaded) метод, який приймає три параметра і третій параметр - це як раз бажана точність точніст.

2023-11-07 21:44 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertThrows(NullPointerException.class, () -> three.distanceToPoint(two));
виклик будь-чого на `null` завжди призводить до NPE. це поведінка JVM. ми ж маємо тестувати поведінку нашого коду.

2023-11-07 23:03 UTC, ShevOleks commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +    private static Point one, two;
Прибрав static та замінив аннотацію @BeforeAll на @BeforeEach

2023-11-07 23:14 UTC, ShevOleks commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertEquals(Math.sqrt(2), result);
коли думав над реалізацією - згадав, що порівняння повинно бути з точністю, але чомусь забув коли вже писав код... А от що у методі є дельта - сам не побачив. Дякую!

2023-11-07 23:34 UTC, ShevOleks commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertThrows(NullPointerException.class, () -> three.distanceToPoint(two));
видалив даний тест

2023-11-07 23:47 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertEquals(Math.sqrt(2), result);
1) 0.001 доцільно було винести у статичну константу, оскільки точність обчислення від тестових параметрів не залежить і скрізь мала б бути однаковою. 
2) Чомусь не в усі тести додав точність `Assertions.assertEquals(-1, result);` - тут же ти так само порівнюєш два `double`

2023-11-07 23:58 UTC, ShevOleks commented on src/test/java/ua/vodafone/lesson10/PointTest.java
> +        Assertions.assertEquals(Math.sqrt(2), result);
не додав тому, що значення -1 отримується не в результаті якихось обчислень, а суто присвоєнням

2023-11-08 00:11 UTC, JIeIIIa approved these changes

2023-11-08 07:16 UTC, merged