L14-HW22. Initial commit.
ShevOleks/Shevchenko_JavaBase2023_03-10-2023 pull request #12
Opened 2023-11-09 13:54 UTC by ShevOleks

2023-11-09 19:30 UTC, JIeIIIa requested changes

2023-11-09 19:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lesson14/MusicStyles.java
> +    String team;
забув про інкапсуляцію (модифікатор доступу та геттер)

2023-11-09 19:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lesson14/ClassicMusic.java
> +        this.team = team;
якщо team обов'язково має бути заповнено, то краще зробити конструктор з параметром у абстрактному класі, і тут викликати конструтор батьківського класу

2023-11-14 13:07 UTC, ShevOleks commented on src/main/java/ua/vodafone/lesson14/MusicStyles.java
> +    String team;
зробив private і додав getter

2023-11-14 13:10 UTC, ShevOleks commented on src/main/java/ua/vodafone/lesson14/ClassicMusic.java
> +        this.team = team;
done

2023-11-14 13:28 UTC, JIeIIIa approved these changes

2023-11-14 20:32 UTC, merged