Lesson8 - HW12.
ShevOleks/Shevchenko_JavaBase2023_03-10-2023 pull request #2
Opened 2023-10-16 15:29 UTC by ShevOleks

Home work 12.

2023-10-16 23:12 UTC, JIeIIIa requested changes

2023-10-16 23:12 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +        int[] minElements = selectMinimumForRows(array);
Така реалізація методу не підійде. Я задав 10 рядків, 6 з них виявились порожніми. Тепер я дивлюсь на вивід:
```
Minimal elements of each existing row are:  81 42 62 95
```
і не розумію 42 якому номеру рядка відповідає.

2023-10-16 23:12 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +        return minElements[0];
Ок, а якщо `minElements` буде порожнім? Задай кількість рядків 10, макс кількість елементів у рядку 1 (M==1) і подивись що буде.

2023-10-16 23:12 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +    private static void divideArrayElements(int[][] array, int absoluteMinimum) {
Код не буде працювати якщо `abcoluteMinimum == 0` А такий випадок можливий.

2023-10-17 17:41 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +    private static void divideArrayElements(int[][] array, int absoluteMinimum) {
Перед викликом цього методу виконується перевірка на abcoluteMinimum == 0 (рядки 57-60)

2023-10-19 13:58 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +        int[] minElements = selectMinimumForRows(array);
Зробив вивід номеру рядка для кожного значення мінімуму або налу.

2023-10-19 13:58 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +        return minElements[0];
додав логіку обробки значень "нал"

2023-10-19 22:29 UTC, JIeIIIa requested changes
Загальне зауваження до багатьох методів: ти передаєш `minValue` і значення на 1 менше вважаєш за `null`. Так робити можна, але код стає менш зрозумілим. Наприклад, якщо я дивлюсь окремо на виклик метода для знаходження суму, то чому в методи ще якесь мінімальне значення треба передати і що це за мінімальне значення має бути - не зрозуміло.
Натомість краще зробити статичну константу для цілого значення, яке ти завжди будеш трактувати як `null`. Для значення константи більш за все підходять мін/макс значення для `int`. Відповідні значення є в класі-обгортці: `Integer.MIN_VALUE`/`Integer.MAX_VALUE`. Тоді при генерації ти забороняєш використання значення, яке трактується як `null` і в методи не потрібно передавати "зайвий" не зрозумілий параметр.

2023-10-19 22:29 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +    private static void divideArrayElements(int[][] array, int absoluteMinimum) {
Мабуть, я не уважно подивився. Сорри. Але дану перевірку доцільніше робити в середині методу. Якщо на `absoluteMinimum` ділити не можна (а це 0 або ж не існує), то нічого не робити і виводити помилку. У тебе зараз помилка тільки для 0 виводиться

2023-10-19 22:29 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +        if (sum != minValue - 1) {
Тут можна було не ускладнювати і для порожньому матриці вважати суму 0.
В твої реалізація сума зараз рахується не вірно. Перевір який результат буде для такої матриці:
```
System.out.println(sumOfArray(new int[][]{{1, 2, 3}}, 0));
```

2023-10-23 12:27 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +    private static void divideArrayElements(int[][] array, int absoluteMinimum) {
Переніс перевірку у метод.

2023-10-23 12:32 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +        if (sum != minValue - 1) {
Виправив помилку при підрахункку суми масиву.
Використовувати Integer.MIN_VALUE як значення null не став, тому що у цьому випадку не можна буде наповнювати масив від'ємними значеннями (або треба переробляти логіку...)

2023-10-23 14:02 UTC, JIeIIIa requested changes

2023-10-23 14:02 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +    static final int minValue = 0;
Code conventions! Статичні константи мають бути в UPPER_CAMEL_CASE

2023-10-23 14:02 UTC, JIeIIIa commented on src/ua/vodafone/lesson8/StepArray.java
> +        if (rows <= 0 || maxSize <= 0 || minValue <= Integer.MIN_VALUE) {
Тут мала б бути рівність `minValue <= Integer.MIN_VALUE`. Константа `minValue` має тип `int` і нічого, що менше мініального значення типу int в дану константу ти не запишеш. За цим слідкує компілятор.

2023-10-26 22:30 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +    static final int minValue = 0;
Fixed

2023-10-26 22:32 UTC, ShevOleks commented on src/ua/vodafone/lesson8/StepArray.java
> +        if (rows <= 0 || maxSize <= 0 || minValue <= Integer.MIN_VALUE) {
Fixed

2023-10-26 22:36 UTC, merged