Lesson10 hw16
ShevOleks/Shevchenko_JavaBase2023_03-10-2023 pull request #6
Opened 2023-10-26 22:20 UTC by ShevOleks

2023-10-27 06:57 UTC, JIeIIIa requested changes

2023-10-27 06:57 UTC, JIeIIIa commented on src/ua/vodafone/lesson10/Point.java
> +    public String getCoordinates() {
а навіщо цей метод, якщо є `toString()`?

2023-10-27 06:57 UTC, JIeIIIa commented on src/ua/vodafone/lesson10/Point.java
> +    public static double distanceBetweenPoints(Point first, Point second) {
Було ось таке зауваження і воно, на жаль, не враховано

> і ще про клас Point: враховуйте, що методи мають працювати безпечно. Тобто не викидати неочікувано NullPointerException тощо

2023-10-27 06:57 UTC, JIeIIIa commented on src/ua/vodafone/lesson10/Point.java
> +        return (this.ordinate == somePoint.ordinate && this.abscissa == somePoint.abscissa);
дужки тут зайві, імхо. вони не роблять код простішим для читання...

2023-10-27 06:57 UTC, JIeIIIa commented on src/ua/vodafone/lesson10/PointDemo.java
> +        System.out.println("Compare for points One and Two is: " + one.equals(two));
бажано б було ще через `==` порівняти обʼєкти, щоб показати що це два різних обʼєкта. тому що тут ти демонструєш, що значення рівні

2023-10-27 20:14 UTC, ShevOleks commented on src/ua/vodafone/lesson10/Point.java
> +    public String getCoordinates() {
тому що при обговоренні домашки сказали, що потрібен окремий метод, котрий буде повертати обидві координати точки і ще один метод для запису координат

2023-10-27 20:17 UTC, ShevOleks commented on src/ua/vodafone/lesson10/Point.java
> +    public static double distanceBetweenPoints(Point first, Point second) {
а яким чином тут буде нал, якщо конструктор зобов'язує вказати координати при створенні, і координати це int, котрий не може бути налом?

2023-10-27 20:19 UTC, ShevOleks commented on src/ua/vodafone/lesson10/Point.java
> +        return (this.ordinate == somePoint.ordinate && this.abscissa == somePoint.abscissa);
згоден...
зараз і сам не знаю, чому я їх поставив... можливо там щось експерементував і потім прибрав, а дужки забув...

2023-10-27 20:20 UTC, ShevOleks commented on src/ua/vodafone/lesson10/PointDemo.java
> +        System.out.println("Compare for points One and Two is: " + one.equals(two));
ок, додам порівняння посилань

2023-10-30 14:20 UTC, JIeIIIa approved these changes

2023-10-30 14:20 UTC, JIeIIIa commented on src/ua/vodafone/lesson10/Point.java
> +    public static double distanceBetweenPoints(Point first, Point second) {
Спробуй написати в коді:
```
Point.distanceBetweenPoints(null, null);
```

2023-10-30 21:03 UTC, ShevOleks commented on src/ua/vodafone/lesson10/Point.java
> +    public static double distanceBetweenPoints(Point first, Point second) {
якщо так - тоді зрозуміло...

2023-10-30 21:03 UTC, merged